# Generated by Django 3.0.6 on 2020-05-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalsettings",
            options={"verbose_name": "global settings", "verbose_name_plural": "global settings"},
        ),
    ]
