# Generated by Django 3.0.6 on 2020-05-31 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_auto_20200531_1747"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsettings",
            name="allow_registration",
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="event_state",
            field=models.CharField(
                choices=[
                    ("PRE_EVENT", "pre-event"),
                    ("DOORS_OPEN", "doors open"),
                    ("GRID_OPEN", "grid open"),
                    ("POST_EVENT", "post-event"),
                ],
                default="PRE_EVENT",
                max_length=10,
            ),
        ),
    ]
