# Generated by Django 3.1.1 on 2020-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200531_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="breakout_category_id",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
